version: '3.8'

networks:
  fintech-net:
    external: true

services:
  wallet-service:
    build: .
    container_name: wallet-service
    ports:
      - "8082:8080" # Porta Exposta 8082
    environment:
      - POSTGRES_URL=jdbc:postgresql://fintech-postgres:5432/fintech_db
      - REDIS_HOST=fintech-redis
      - RABBITMQ_HOST=fintech-rabbitmq
    networks:
      - fintech-net